name: Python application test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Navigate to python directory
      run: cd ./python
    - name: Install dependencies
      run: |
        cd ./python
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run pytest on test_*.py files in ./python
      run: |
        cd ./python
        find . -name 'test_*.py' -exec pytest {} +
